import pipesImage from "../../../static/truby.jpg";
import ribbonImage from "../../../static/lenta.jpg";
import wireImage from "../../../static/provoloka.jpg";
import rodImage from "../../../static/prutok.jpg";
import listImage from "../../../static/listy.jpg";

export const goodsList = [
  {
    id: 1,
    name: "Труба ВГП",
    type: "pipe",
    size: "40x3мм",
    price: 5.52,
    image: pipesImage,
  },
  {
    id: 2,
    name: "Труба профильная",
    type: "pipe",
    size: "20x10x2мм",
    price: 1.69,
    image: pipesImage,
  },
  {
    id: 3,
    name: "Труба котловая",
    type: "pipe",
    size: "352x8мм",
    price: 281.5,
    image: pipesImage,
  },
  {
    id: 4,
    name: "Монтажная лента",
    type: "ribbon",
    series: "BAD 206",
    price: 111.25,
    image: ribbonImage,
  },
  {
    id: 5,
    name: "Монтажная лента",
    type: "ribbon",
    series: "BAD 210",
    price: 132.5,
    image: ribbonImage,
  },
  {
    id: 6,
    name: "Монтажная лента",
    type: "ribbon",
    series: "BAD 212",
    price: 141.25,
    image: ribbonImage,
  },
  {
    id: 7,
    name: "Проволока (т/н жесткая)",
    type: "wire",
    series: "Д. 2,0",
    price: 5.5,
    image: wireImage,
  },
  {
    id: 8,
    name: "Проволока (т/н жесткая)",
    type: "wire",
    series: "Д. 2,5",
    price: 7,
    image: wireImage,
  },
  {
    id: 9,
    name: "Проволока (т/н жесткая)",
    type: "wire",
    series: "Д. 3",
    price: 10,
    image: wireImage,
  },
  {
    id: 10,
    name: "Пруток",
    type: "rod",
    series: "Д16Т Ф 8-30",
    price: 14,
    image: rodImage,
  },
  {
    id: 11,
    name: "Пруток",
    type: "rod",
    series: "Д19Т Ф 9-31",
    price: 18,
    image: rodImage,
  },
  {
    id: 12,
    name: "Пруток",
    type: "rod",
    series: "Д21Т Ф 10-32",
    price: 22,
    image: rodImage,
  },
  {
    id: 13,
    name: "Лист холоднокатный",
    type: "list",
    size: "1,0x1250x2500",
    price: 50,
    image: listImage,
  },
  {
    id: 14,
    name: "Лист горячекатный",
    type: "list",
    size: "1,0x1250x2500",
    price: 66,
    image: listImage,
  },
  {
    id: 15,
    name: "Лист рифлёный",
    type: "list",
    size: "1,0x1250x2500",
    price: 550,
    image: listImage,
  },
];

export const materials = [
  "Медь",
  "Бронза",
  "Латунь",
  "Алюминий",
  "Никель",
  "Титан",
  "Молибден",
  "Вольфрам",
  "Цинк",
  "Олово",
  "Цирконий",
  "Хром",
];
